const hamburguesas = [
    {
        nombre: "Buzzburger",
        tipoDeQueso: "cheddar",
        verduras: "lechuga, jitomate",
        aderezos: "BuzzSauce",
        adicionales: false, 
        precio: 600, 
    },
    {
        nombre: "Cheeseburger",
        tipoDeQueso: "cheddar",
        verduras: false,
        aderezos: "BuzzSauce",
        adicionales: false, 
        precio: 500, 
    },
    {
        nombre: "Chili Buzzburger",
        tipoDeQueso: "cheddar",
        verduras: false,
        aderezos: "Mostaza Suave",
        adicionales: "Chile Picante, pickles", 
        precio: 700, 
    },
    {
        nombre: "Butter Buzzburger",
        tipoDeQueso: "cheddar",
        verduras: false,
        aderezos: false,
        adicionales: "cebolla reahogada en manteca y fondo de carne, manteca", 
        precio: 600, 
    },
    {
        nombre: "Double-Double Buzzburger",
        tipoDeQueso: "cheddar",
        verduras: "lechuga, tomate, lonja de cebolla",
        aderezos: "BuzzSauce",
        adicionales: false, 
        precio: 600, 
    },
    {
        nombre: "Smoke Buzz",
        tipoDeQueso: "cheddar",
        verduras: "aji",
        aderezos: "BuzzSauce",
        adicionales: "bacon", 
        precio: 600, 
    },
]